import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#9ca0a2",
        "surface-dim": "#ccdbf4",
        "surface-container": "#e5eeff",
        error: "#ba1a1a",
        primary: "#182232",
        "surface-container-highest": "#d4e4fc",
        "on-tertiary-fixed-variant": "#434749",
        "on-surface-variant": "#45474c",
        "surface-tint": "#555f71",
        "tertiary-fixed-dim": "#c3c7c9",
        "on-primary-container": "#96a0b5",
        background: "#f8f9ff",
        "on-error-container": "#93000a",
        "inverse-primary": "#bdc7dc",
        "on-secondary-container": "#28705b",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c5c6cd",
        "tertiary-fixed": "#e0e3e5",
        "secondary-fixed": "#a9f1d7",
        "on-tertiary-fixed": "#181c1e",
        "surface-container-high": "#dce9ff",
        "on-background": "#0d1c2e",
        "primary-container": "#2d3748",
        "surface-container-low": "#eff4ff",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "primary-fixed-dim": "#bdc7dc",
        "on-primary": "#ffffff",
        "inverse-surface": "#223144",
        "error-container": "#ffdad6",
        "tertiary-container": "#333739",
        outline: "#75777d",
        "on-primary-fixed": "#121c2c",
        "on-primary-fixed-variant": "#3d4759",
        "secondary-fixed-dim": "#8ed5bc",
        "on-secondary-fixed": "#002118",
        "on-surface": "#0d1c2e",
        "primary-fixed": "#d9e3f9",
        secondary: "#206a56",
        tertiary: "#1e2223",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#a9f1d7",
        "on-error": "#ffffff",
        surface: "#f8f9ff",
        "on-secondary-fixed-variant": "#00513f",
        "surface-variant": "#d4e4fc",
        "surface-bright": "#f8f9ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "container-max": "1280px",
        "margin-desktop": "40px",
        gutter: "24px",
        base: "8px",
      },
      fontFamily: {
        headline: ["var(--font-manrope)"],
        body: ["var(--font-inter)"],
        mono: ["var(--font-jetbrains-mono)"],
      },
    },
  },
  plugins: [],
};
export default config;
